name = "glx"
version = "0.2.0"
description = "Extensions to the Gleam standard library."
licences = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "glx" }

[dependencies]
gleam_stdlib = "~> 0.29"

[dev-dependencies]
gleeunit = "~> 0.10"
