name = "glx"
version = "0.3.1"
description = "Extensions to the Gleam standard library."
licences = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "glx" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
